name: Build and Push to GHCR

on:
  push:
    tags:
      # - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'release-*'
      - 'v*'

# Required permissions to push to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract tag name
        id: vars
        run: |
          # Full tag: v10.11.5.001
          FULL_TAG=${GITHUB_REF#refs/tags/}

          # Stripped tag: v10.11.5 (removes the last .suffix)
          STRIPPED_TAG=${FULL_TAG%.*}

          echo "repo_tag=${FULL_TAG}" >> $GITHUB_OUTPUT
          echo "jellyfin_tag=${STRIPPED_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker
          build-args: |
            JELLYFIN_TAG=${{ steps.vars.outputs.jellyfin_tag }}
          #   # JELLYFIN_BRANCH=release-10.11.z
          #   SOME_OTHER_VAR=hello-world
          push: true
          # Note: repository name is converted to lowercase for GHCR compatibility
          tags: |
            ghcr.io/${{ github.repository_owner }}/jellyfin-tizen-installer:${{ steps.vars.outputs.repo_tag }}
            ghcr.io/${{ github.repository_owner }}/jellyfin-tizen-installer:latest
